### ISSUE TITLE
发版这么快，能不能把演示地址的账户密码弄上

### ISSUE THREAD

**Issue by tingfeng-key** [flingyp/vue-plus-admin#1]
发版这么快，能不能把演示地址的账户密码弄上，用admin/admin登录都没得反应

**Comment by flingyp** [comment]
Sign up 是 注册 、Sign in 是 登录。

盲猜一波你是不是在Sign up 输入的😂。

默认账号：admin/admin 和 user/user

![image](https://github.com/flingyp/vadmire-admin/assets/57666140/a050d8c8-8fbd-44a5-ad0c-06b7d1edcd25)


![image](https://github.com/flingyp/vadmire-admin/assets/57666140/9f1e34eb-f994-4194-8a4a-90d150b54a05)

**Comment by flingyp** [comment]
后期考虑把注册表单拿掉吧。

**Comment by tingfeng-key** [comment]
对对对，猜对了，后台还挺好看的，干巴爹

**Comment by flingyp** [comment]
哈哈哈，谢谢。如果有啥其他的想法可以分享一下哦。
